export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_ITEM = 'add_item'
export const Login_NAME = 'login_name'
export const Login_PWD = 'login_pwd'
export const Login = 'login'
export const Sign = 'Sign'
//export const Login_isAuth_F = 'login_isAuth_false'
//export const Login_isAuth_T = 'login_isAuth_true'